name: 'Self test MooseCI'
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - uses: ./
              with:
                project-path: test-fixture
            - uses: actions/download-artifact@v4
              with:
                name: moose-ci-report
            - name: 'Check report exists'
              working-directory: .
              run: test -f test-fixture/.moose-ci/report/report*.json