name: 'Self test'
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - uses: ./
              with:
                project-path: test-fixture
                report-path: test-fixture/.moose-ci/report
            - uses: actions/download-artifact@v4
              with:
                name: moose-ci-report
            - name: 'Check report exists'
              working-directory: .
              run: test -f test-fixture/.moose-ci/report/report*.json